from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .views import (
    CustomTokenObtainPairView,
    CustomRefreshTokenView,
    CurrentUserView,
    DictionaryEntryViewSet,
    MachineViewSet,
    MaintenanceTypesView,
    is_authenticated,
    logout,
    MachineSearchAPIView,
    MachineListView,
    MachineDetailView,
    machine_form_options,
    machine_update,
    machine_create,
    machine_delete,
    DictEntryListView,
    DictEntryDetailView,
    dict_entry_update,
    dict_entry_create,
    dict_entry_delete,
    MaintenanceListView,
    MaintenanceDetailView,
    MaintenanceCreateView,
    MaintenanceDeleteView,
    MaintenanceUpdateView,
    ClaimViewSet,
)


router = DefaultRouter()

router.register(
    prefix=r"claims",
    viewset=ClaimViewSet,
    basename="claim",
)

# вспомогалки для дёрганья инфы для выпадашек
router.register(
    prefix=r'dictionary-entries',
    viewset=DictionaryEntryViewSet,
    basename='dictionary-entry',
)
router.register(
    prefix=r'machines',
    viewset=MachineViewSet,
    basename='machine',
)

urlpatterns = [
    path(
        route="login",
        view=CustomTokenObtainPairView.as_view(),
        name="login",
    ),
    path(
        route="token-refresh",
        view=CustomRefreshTokenView.as_view(),
        name="token-refresh",
    ),
    path(
        route="logout",
        view=logout,
        name="logout",
    ),
    path(
        route="user",
        view=CurrentUserView.as_view(),
        name="current-user",
    ),
    path(
        route="authenticated",
        view=is_authenticated,
        name="is-authenticated",
    ),
    path(
        route="machines/search",
        view=MachineSearchAPIView.as_view(),
        name="machine-search",
    ),

    #
    path(
        route='machines',
        view=MachineListView.as_view(),
        name='machine-list',
    ),
    path(
        route='machines/<int:pk>',
        view=MachineDetailView.as_view(),
        name='machine-detail',
    ),
    path(
        route='machine-form-options/',
        view=machine_form_options,
        name='machine-form-options',
    ),
    path(
        route='machine-update/<int:pk>',
        view=machine_update,
        name='machine-update',
    ),
    path(
        route='machine-create',
        view=machine_create,
        name='machine-create',
    ),
    path(
        route='machine-delete/<int:pk>',
        view=machine_delete,
        name='machine-delete',
    ),

    #
    path(
        route='dict-entries',
        view=DictEntryListView.as_view(),
        name='dict-entry-list',
    ),
    path(
        route='dict-entries/<int:pk>',
        view=DictEntryDetailView.as_view(),
        name='dict-entry-detail',
    ),
    path(
        route='dict-entry-update/<int:pk>',
        view=dict_entry_update,
        name='dict-entry-update',
    ),
    path(
        route='dict-entry-create',
        view=dict_entry_create,
        name='dict-entry-create',
    ),
    path(
        route='dict-entry-delete/<int:pk>',
        view=dict_entry_delete,
        name='dict-entry-delete',
    ),

    #
    path(
        route='maintenance',
        view=MaintenanceListView.as_view(),
        name='maintenance-list',
    ),
    path(
        route='maintenance/<int:pk>',
        view=MaintenanceDetailView.as_view(),
        name='maintenance-detail',
    ),
    path(
        route='maintenance-types',
        view=MaintenanceTypesView.as_view(),
        name='maintenance-types',
    ),
    path(
        route='maintenance-update/<int:pk>',
        view=MaintenanceUpdateView.as_view(),
        name='maintenance-update',
    ),
    path(
        route='maintenance-create',
        view=MaintenanceCreateView.as_view(),
        name='maintenance-create',
    ),
    path(
        route='maintenance-delete/<int:pk>',
        view=MaintenanceDeleteView.as_view(),
        name='maintenance-delete',
    ),

    #
    path(
        '',
        include(router.urls),
    ),
]
