version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    volumes:
      - ./backend:/app
    networks:
      - silant-network
    restart: unless-stopped

  frontend:
    build: ./frontend/silant
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/silant:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - silant-network
    environment:
      - HOST=0.0.0.0
    stdin_open: true
    tty: true

networks:
  silant-network:
    driver: bridge

volumes:
  django-data: